# Generated by Django 5.2.7 on 2026-06-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_integrity', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentcheck',
            new_name='content_int_course__b4101d_idx',
            old_name='ci_course_status_idx',
        ),
        migrations.AlterField(
            model_name='contentcheck',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contentcheck',
            name='score',
            field=models.FloatField(blank=True, help_text='Similarity / match percentage returned by the provider, 0-100', null=True),
        ),
        migrations.AlterField(
            model_name='coursereport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursereport',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='False while some components are still pending/queued.'),
        ),
    ]
